//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Работа_для_работы
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Coтрудники = new HashSet<Coтрудники>();
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int id_заказа { get; set; }
        public string Дата_исполнения { get; set; }
        public string C__Договора { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public Nullable<int> id_статус_заказа { get; set; }
    
        public virtual Клиeнты Клиeнты { get; set; }
        public virtual Статусы_заказов Статусы_заказов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coтрудники> Coтрудники { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги> Услуги { get; set; }
    }
}
